[package]
name = "aws-gamelift-server-sdk-rs"
version = "0.1.0"
authors = ["Alexander Zaitsev <zamazan4ik@tut.by>"]
edition = "2018"

[features]
default = ["with-serde"]
with-serde = ["protobuf/with-serde"]

[dependencies]
bytes = "1.0.1"
futures-util = { version = "0.3.15", features = ["sink"] }
log = "0.4.14"
protobuf = { version = "2.23.0", features = ["with-serde"] }
reqwest = "0.11.3"
serde = "1.0.126"
serde_json = "1.0.64"
strum = "0.20.0"
strum_macros = "0.20.1"
thiserror = "1.0.24"
tokio = { version = "1.5.0", features = ["macros", "net", "rt-multi-thread", "time"] }
tokio-tungstenite = "0.14.0"

[build-dependencies]
protobuf-codegen-pure = "2.23.0"

[dev-dependencies]
env_logger = "0.8.3"

[profile.release]
opt-level = 3
lto = true
